/**
 * Global Mobilis — Destinations API
 * Server functions for fetching and searching destination data.
 * Gracefully handles missing database by returning seed data inline.
 */
import { createServerFn } from "@tanstack/react-start";
import type { Destination } from "~/db.types";

// =============================================================================
// Inline seed data (used when database is not connected)
// =============================================================================
export const SEED_DESTINATIONS: Destination[] = [
  { id: "1", country: "Canada", city: "Toronto", region: "Ontario", continent: "North America", flag_emoji: "🇨🇦", image_url: "", job_score: 92, education_score: 88, business_score: 90, tourism_score: 85, quality_of_life_score: 87, safety_score: 82, avg_rent_1br: 1800, avg_rent_3br: 3200, cost_of_living_index: 78.5, avg_monthly_utilities: 150, avg_monthly_groceries: 400, avg_monthly_transport: 130, description: "Canada's largest city — a global hub for finance, tech, and culture with unmatched diversity.", short_description: "Canada's largest city — a global hub for finance, tech, and culture with unmatched diversity.", languages: ["English", "French"], currency: "CAD", timezone: "America/Toronto", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "2", country: "Canada", city: "Vancouver", region: "British Columbia", continent: "North America", flag_emoji: "🇨🇦", image_url: "", job_score: 78, education_score: 80, business_score: 75, tourism_score: 92, quality_of_life_score: 85, safety_score: 85, avg_rent_1br: 2200, avg_rent_3br: 3800, cost_of_living_index: 85.2, avg_monthly_utilities: 160, avg_monthly_groceries: 420, avg_monthly_transport: 120, description: "A stunning coastal city where mountains meet ocean.", short_description: "A stunning coastal city where mountains meet ocean.", languages: ["English", "French", "Chinese"], currency: "CAD", timezone: "America/Vancouver", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "3", country: "United Kingdom", city: "London", region: "England", continent: "Europe", flag_emoji: "🇬🇧", image_url: "", job_score: 95, education_score: 92, business_score: 93, tourism_score: 90, quality_of_life_score: 80, safety_score: 70, avg_rent_1br: 2100, avg_rent_3br: 3800, cost_of_living_index: 82.3, avg_monthly_utilities: 180, avg_monthly_groceries: 380, avg_monthly_transport: 150, description: "One of the world's great global cities — finance, culture, and endless opportunity.", short_description: "One of the world's great global cities — finance, culture, and endless opportunity.", languages: ["English"], currency: "GBP", timezone: "Europe/London", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "4", country: "Germany", city: "Berlin", region: "Berlin", continent: "Europe", flag_emoji: "🇩🇪", image_url: "", job_score: 85, education_score: 82, business_score: 88, tourism_score: 88, quality_of_life_score: 83, safety_score: 80, avg_rent_1br: 1200, avg_rent_3br: 2200, cost_of_living_index: 65.3, avg_monthly_utilities: 200, avg_monthly_groceries: 350, avg_monthly_transport: 90, description: "Europe's startup capital — affordable, creative, and buzzing with opportunity.", short_description: "Europe's startup capital — affordable, creative, and buzzing with opportunity.", languages: ["German", "English"], currency: "EUR", timezone: "Europe/Berlin", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "5", country: "Germany", city: "Munich", region: "Bavaria", continent: "Europe", flag_emoji: "🇩🇪", image_url: "", job_score: 88, education_score: 85, business_score: 82, tourism_score: 85, quality_of_life_score: 90, safety_score: 85, avg_rent_1br: 1500, avg_rent_3br: 2800, cost_of_living_index: 72.1, avg_monthly_utilities: 220, avg_monthly_groceries: 380, avg_monthly_transport: 85, description: "Where Bavarian tradition meets German engineering.", short_description: "Where Bavarian tradition meets German engineering.", languages: ["German", "English"], currency: "EUR", timezone: "Europe/Berlin", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "6", country: "Australia", city: "Sydney", region: "New South Wales", continent: "Oceania", flag_emoji: "🇦🇺", image_url: "", job_score: 88, education_score: 85, business_score: 82, tourism_score: 95, quality_of_life_score: 90, safety_score: 80, avg_rent_1br: 2000, avg_rent_3br: 3800, cost_of_living_index: 80.1, avg_monthly_utilities: 180, avg_monthly_groceries: 450, avg_monthly_transport: 140, description: "Australia's iconic harbor city — sun, surf, and a world-class economy.", short_description: "Australia's iconic harbor city — sun, surf, and a world-class economy.", languages: ["English"], currency: "AUD", timezone: "Australia/Sydney", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "7", country: "Australia", city: "Melbourne", region: "Victoria", continent: "Oceania", flag_emoji: "🇦🇺", image_url: "", job_score: 85, education_score: 90, business_score: 80, tourism_score: 88, quality_of_life_score: 88, safety_score: 82, avg_rent_1br: 1600, avg_rent_3br: 3000, cost_of_living_index: 75.3, avg_monthly_utilities: 170, avg_monthly_groceries: 420, avg_monthly_transport: 130, description: "Australia's cultural capital — world-class coffee, arts, and livability.", short_description: "Australia's cultural capital — world-class coffee, arts, and livability.", languages: ["English"], currency: "AUD", timezone: "Australia/Melbourne", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "8", country: "United Arab Emirates", city: "Dubai", region: "Dubai", continent: "Asia", flag_emoji: "🇦🇪", image_url: "", job_score: 90, education_score: 75, business_score: 95, tourism_score: 92, quality_of_life_score: 80, safety_score: 88, avg_rent_1br: 1600, avg_rent_3br: 3200, cost_of_living_index: 75.8, avg_monthly_utilities: 200, avg_monthly_groceries: 400, avg_monthly_transport: 80, description: "A global business hub with zero income tax and unmatched ambition.", short_description: "A global business hub with zero income tax and unmatched ambition.", languages: ["Arabic", "English", "Hindi"], currency: "AED", timezone: "Asia/Dubai", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "9", country: "Singapore", city: "Singapore", region: "Central", continent: "Asia", flag_emoji: "🇸🇬", image_url: "", job_score: 92, education_score: 90, business_score: 95, tourism_score: 85, quality_of_life_score: 88, safety_score: 95, avg_rent_1br: 2500, avg_rent_3br: 4500, cost_of_living_index: 88.5, avg_monthly_utilities: 150, avg_monthly_groceries: 500, avg_monthly_transport: 100, description: "Asia's most dynamic city-state — finance, safety, and world-class education.", short_description: "Asia's most dynamic city-state — finance, safety, and world-class education.", languages: ["English", "Mandarin", "Malay", "Tamil"], currency: "SGD", timezone: "Asia/Singapore", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "10", country: "Netherlands", city: "Amsterdam", region: "North Holland", continent: "Europe", flag_emoji: "🇳🇱", image_url: "", job_score: 82, education_score: 78, business_score: 85, tourism_score: 90, quality_of_life_score: 85, safety_score: 82, avg_rent_1br: 1700, avg_rent_3br: 3000, cost_of_living_index: 75.0, avg_monthly_utilities: 180, avg_monthly_groceries: 380, avg_monthly_transport: 100, description: "Bike-friendly, progressive, and a hub for tech and innovation.", short_description: "Bike-friendly, progressive, and a hub for tech and innovation.", languages: ["Dutch", "English"], currency: "EUR", timezone: "Europe/Amsterdam", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "11", country: "New Zealand", city: "Auckland", region: "Auckland", continent: "Oceania", flag_emoji: "🇳🇿", image_url: "", job_score: 75, education_score: 78, business_score: 72, tourism_score: 90, quality_of_life_score: 90, safety_score: 85, avg_rent_1br: 1600, avg_rent_3br: 2800, cost_of_living_index: 72.5, avg_monthly_utilities: 150, avg_monthly_groceries: 400, avg_monthly_transport: 120, description: "New Zealand's largest city — stunning landscapes meet a relaxed lifestyle.", short_description: "New Zealand's largest city — stunning landscapes meet a relaxed lifestyle.", languages: ["English", "Maori"], currency: "NZD", timezone: "Pacific/Auckland", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "12", country: "Ireland", city: "Dublin", region: "Leinster", continent: "Europe", flag_emoji: "🇮🇪", image_url: "", job_score: 85, education_score: 80, business_score: 82, tourism_score: 78, quality_of_life_score: 80, safety_score: 78, avg_rent_1br: 1800, avg_rent_3br: 3200, cost_of_living_index: 78.0, avg_monthly_utilities: 200, avg_monthly_groceries: 380, avg_monthly_transport: 120, description: "Europe's tech capital — home to global tech giants and a young workforce.", short_description: "Europe's tech capital — home to global tech giants.", languages: ["English", "Irish"], currency: "EUR", timezone: "Europe/Dublin", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "13", country: "United States", city: "New York", region: "New York", continent: "North America", flag_emoji: "🇺🇸", image_url: "", job_score: 95, education_score: 90, business_score: 95, tourism_score: 95, quality_of_life_score: 75, safety_score: 65, avg_rent_1br: 3500, avg_rent_3br: 6000, cost_of_living_index: 100.0, avg_monthly_utilities: 200, avg_monthly_groceries: 550, avg_monthly_transport: 130, description: "The ultimate global city — finance, culture, and career opportunity at its peak.", short_description: "The ultimate global city — finance, culture, and career opportunity.", languages: ["English", "Spanish", "Chinese"], currency: "USD", timezone: "America/New_York", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "14", country: "United States", city: "San Francisco", region: "California", continent: "North America", flag_emoji: "🇺🇸", image_url: "", job_score: 92, education_score: 85, business_score: 95, tourism_score: 85, quality_of_life_score: 70, safety_score: 60, avg_rent_1br: 3500, avg_rent_3br: 6500, cost_of_living_index: 98.5, avg_monthly_utilities: 180, avg_monthly_groceries: 500, avg_monthly_transport: 120, description: "The heart of global innovation — Silicon Valley's gateway city.", short_description: "The heart of global innovation — Silicon Valley's gateway city.", languages: ["English", "Spanish", "Chinese"], currency: "USD", timezone: "America/Los_Angeles", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "15", country: "Portugal", city: "Lisbon", region: "Lisbon", continent: "Europe", flag_emoji: "🇵🇹", image_url: "", job_score: 72, education_score: 70, business_score: 75, tourism_score: 92, quality_of_life_score: 82, safety_score: 85, avg_rent_1br: 1000, avg_rent_3br: 1800, cost_of_living_index: 55.0, avg_monthly_utilities: 120, avg_monthly_groceries: 300, avg_monthly_transport: 50, description: "Europe's sunny gem — affordable, welcoming, and a digital nomad hotspot.", short_description: "Europe's sunny gem — affordable, welcoming, and a digital nomad hotspot.", languages: ["Portuguese", "English"], currency: "EUR", timezone: "Europe/Lisbon", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "16", country: "Japan", city: "Tokyo", region: "Tokyo", continent: "Asia", flag_emoji: "🇯🇵", image_url: "", job_score: 85, education_score: 88, business_score: 82, tourism_score: 92, quality_of_life_score: 80, safety_score: 90, avg_rent_1br: 1400, avg_rent_3br: 2800, cost_of_living_index: 72.0, avg_monthly_utilities: 180, avg_monthly_groceries: 400, avg_monthly_transport: 80, description: "A fascinating blend of tradition and cutting-edge innovation.", short_description: "A fascinating blend of tradition and cutting-edge innovation.", languages: ["Japanese", "English"], currency: "JPY", timezone: "Asia/Tokyo", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "17", country: "Spain", city: "Barcelona", region: "Catalonia", continent: "Europe", flag_emoji: "🇪🇸", image_url: "", job_score: 70, education_score: 72, business_score: 75, tourism_score: 95, quality_of_life_score: 80, safety_score: 75, avg_rent_1br: 1000, avg_rent_3br: 2000, cost_of_living_index: 58.0, avg_monthly_utilities: 130, avg_monthly_groceries: 320, avg_monthly_transport: 55, description: "Mediterranean lifestyle meets a vibrant tech and startup scene.", short_description: "Mediterranean lifestyle meets a vibrant tech and startup scene.", languages: ["Spanish", "Catalan", "English"], currency: "EUR", timezone: "Europe/Madrid", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  { id: "18", country: "Sweden", city: "Stockholm", region: "Stockholm", continent: "Europe", flag_emoji: "🇸🇪", image_url: "", job_score: 80, education_score: 82, business_score: 78, tourism_score: 80, quality_of_life_score: 90, safety_score: 85, avg_rent_1br: 1400, avg_rent_3br: 2500, cost_of_living_index: 70.0, avg_monthly_utilities: 150, avg_monthly_groceries: 380, avg_monthly_transport: 90, description: "Scandinavian innovation hub — beautiful, sustainable, and family-friendly.", short_description: "Scandinavian innovation hub — beautiful, sustainable, and family-friendly.", languages: ["Swedish", "English"], currency: "SEK", timezone: "Europe/Stockholm", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    // Africa
    { id: "19", country: "South Africa", city: "Cape Town", region: "Western Cape", continent: "Africa", flag_emoji: "🇿🇦", image_url: "", job_score: 72, education_score: 75, business_score: 78, tourism_score: 95, quality_of_life_score: 82, safety_score: 60, avg_rent_1br: 550, avg_rent_3br: 1200, cost_of_living_index: 42.0, avg_monthly_utilities: 80, avg_monthly_groceries: 280, avg_monthly_transport: 60, description: "A breathtaking coastal city where Table Mountain meets vibrant culture and a growing tech scene.", short_description: "Stunning coastal city with mountains, beaches, and a thriving startup ecosystem.", languages: ["English", "Afrikaans", "Xhosa"], currency: "ZAR", timezone: "Africa/Johannesburg", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "20", country: "Kenya", city: "Nairobi", region: "Nairobi", continent: "Africa", flag_emoji: "🇰🇪", image_url: "", job_score: 78, education_score: 72, business_score: 85, tourism_score: 70, quality_of_life_score: 65, safety_score: 55, avg_rent_1br: 500, avg_rent_3br: 1100, cost_of_living_index: 38.0, avg_monthly_utilities: 70, avg_monthly_groceries: 250, avg_monthly_transport: 50, description: "East Africa's economic powerhouse — a hub for innovation, tech startups, and safari adventures.", short_description: "East Africa's tech hub — innovation, safaris, and a booming economy.", languages: ["Swahili", "English"], currency: "KES", timezone: "Africa/Nairobi", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "21", country: "Nigeria", city: "Lagos", region: "Lagos", continent: "Africa", flag_emoji: "🇳🇬", image_url: "", job_score: 80, education_score: 65, business_score: 88, tourism_score: 60, quality_of_life_score: 55, safety_score: 40, avg_rent_1br: 600, avg_rent_3br: 1500, cost_of_living_index: 35.0, avg_monthly_utilities: 100, avg_monthly_groceries: 300, avg_monthly_transport: 40, description: "Africa's largest city — a dynamic megacity of entrepreneurs, creatives, and nonstop energy.", short_description: "Africa's largest city — entrepreneurial energy meets vibrant culture.", languages: ["English", "Yoruba", "Hausa", "Igbo"], currency: "NGN", timezone: "Africa/Lagos", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "22", country: "Ghana", city: "Accra", region: "Greater Accra", continent: "Africa", flag_emoji: "🇬🇭", image_url: "", job_score: 68, education_score: 70, business_score: 72, tourism_score: 75, quality_of_life_score: 70, safety_score: 65, avg_rent_1br: 400, avg_rent_3br: 900, cost_of_living_index: 32.0, avg_monthly_utilities: 60, avg_monthly_groceries: 200, avg_monthly_transport: 35, description: "West Africa's gem — friendly, stable, and growing fast with a rich cultural heritage.", short_description: "West Africa's friendliest city — stable, welcoming, and on the rise.", languages: ["English", "Twi", "Ga"], currency: "GHS", timezone: "Africa/Accra", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "23", country: "Morocco", city: "Casablanca", region: "Casablanca-Settat", continent: "Africa", flag_emoji: "🇲🇦", image_url: "", job_score: 70, education_score: 68, business_score: 75, tourism_score: 80, quality_of_life_score: 72, safety_score: 70, avg_rent_1br: 450, avg_rent_3br: 1000, cost_of_living_index: 38.0, avg_monthly_utilities: 55, avg_monthly_groceries: 220, avg_monthly_transport: 40, description: "Morocco's economic capital — where modern business meets historic charm and Atlantic breezes.", short_description: "Morocco's economic hub — business meets history by the Atlantic.", languages: ["Arabic", "Berber", "French"], currency: "MAD", timezone: "Africa/Casablanca", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "24", country: "Rwanda", city: "Kigali", region: "Kigali", continent: "Africa", flag_emoji: "🇷🇼", image_url: "", job_score: 72, education_score: 78, business_score: 70, tourism_score: 75, quality_of_life_score: 78, safety_score: 85, avg_rent_1br: 400, avg_rent_3br: 850, cost_of_living_index: 30.0, avg_monthly_utilities: 50, avg_monthly_groceries: 180, avg_monthly_transport: 30, description: "Africa's cleanest city — a model of modern urban development and tech innovation.", short_description: "Africa's cleanest city — modern, safe, and innovation-driven.", languages: ["Kinyarwanda", "English", "French", "Swahili"], currency: "RWF", timezone: "Africa/Kigali", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    // South America
    { id: "25", country: "Argentina", city: "Buenos Aires", region: "Buenos Aires", continent: "South America", flag_emoji: "🇦🇷", image_url: "", job_score: 72, education_score: 75, business_score: 78, tourism_score: 90, quality_of_life_score: 75, safety_score: 55, avg_rent_1br: 500, avg_rent_3br: 1000, cost_of_living_index: 40.0, avg_monthly_utilities: 80, avg_monthly_groceries: 250, avg_monthly_transport: 30, description: "The Paris of South America — tango, steak, and a passionate European-infused culture.", short_description: "The Paris of South America — tango, steak, and European charm.", languages: ["Spanish"], currency: "ARS", timezone: "America/Argentina/Buenos_Aires", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "26", country: "Brazil", city: "São Paulo", region: "São Paulo", continent: "South America", flag_emoji: "🇧🇷", image_url: "", job_score: 85, education_score: 80, business_score: 88, tourism_score: 72, quality_of_life_score: 68, safety_score: 40, avg_rent_1br: 600, avg_rent_3br: 1300, cost_of_living_index: 45.0, avg_monthly_utilities: 100, avg_monthly_groceries: 280, avg_monthly_transport: 60, description: "The economic engine of Latin America — a sprawling metropolis of business, culture, and diversity.", short_description: "Latin America's economic powerhouse — business, culture, and endless energy.", languages: ["Portuguese"], currency: "BRL", timezone: "America/Sao_Paulo", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "27", country: "Brazil", city: "Rio de Janeiro", region: "Rio de Janeiro", continent: "South America", flag_emoji: "🇧🇷", image_url: "", job_score: 65, education_score: 70, business_score: 72, tourism_score: 95, quality_of_life_score: 68, safety_score: 35, avg_rent_1br: 550, avg_rent_3br: 1200, cost_of_living_index: 42.0, avg_monthly_utilities: 90, avg_monthly_groceries: 260, avg_monthly_transport: 55, description: "The Marvelous City — iconic beaches, samba, and breathtaking natural beauty.", short_description: "The Marvelous City — beaches, samba, and breathtaking landscapes.", languages: ["Portuguese"], currency: "BRL", timezone: "America/Sao_Paulo", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "28", country: "Chile", city: "Santiago", region: "Santiago Metropolitan", continent: "South America", flag_emoji: "🇨🇱", image_url: "", job_score: 78, education_score: 80, business_score: 82, tourism_score: 78, quality_of_life_score: 82, safety_score: 70, avg_rent_1br: 600, avg_rent_3br: 1300, cost_of_living_index: 48.0, avg_monthly_utilities: 90, avg_monthly_groceries: 280, avg_monthly_transport: 55, description: "Chile's modern capital — surrounded by the Andes, with a stable economy and excellent quality of life.", short_description: "Modern Andean capital — stability, quality of life, and mountain views.", languages: ["Spanish"], currency: "CLP", timezone: "America/Santiago", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "29", country: "Colombia", city: "Bogotá", region: "Bogotá", continent: "South America", flag_emoji: "🇨🇴", image_url: "", job_score: 72, education_score: 72, business_score: 78, tourism_score: 70, quality_of_life_score: 68, safety_score: 50, avg_rent_1br: 400, avg_rent_3br: 900, cost_of_living_index: 32.0, avg_monthly_utilities: 70, avg_monthly_groceries: 200, avg_monthly_transport: 35, description: "Colombia's high-altitude capital — a renaissance city of art, gastronomy, and entrepreneurship.", short_description: "Colombia's renaissance — art, gastronomy, and entrepreneurship at altitude.", languages: ["Spanish"], currency: "COP", timezone: "America/Bogota", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "30", country: "Peru", city: "Lima", region: "Lima", continent: "South America", flag_emoji: "🇵🇪", image_url: "", job_score: 70, education_score: 68, business_score: 72, tourism_score: 85, quality_of_life_score: 68, safety_score: 45, avg_rent_1br: 450, avg_rent_3br: 950, cost_of_living_index: 35.0, avg_monthly_utilities: 65, avg_monthly_groceries: 220, avg_monthly_transport: 35, description: "Peru's coastal capital — world-class cuisine, colonial history, and a gateway to Machu Picchu.", short_description: "World-class cuisine, colonial history, gateway to Machu Picchu.", languages: ["Spanish", "Quechua"], currency: "PEN", timezone: "America/Lima", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    // Caribbean
    { id: "31", country: "Dominican Republic", city: "Santo Domingo", region: "National District", continent: "North America", flag_emoji: "🇩🇴", image_url: "", job_score: 62, education_score: 65, business_score: 70, tourism_score: 88, quality_of_life_score: 68, safety_score: 50, avg_rent_1br: 400, avg_rent_3br: 850, cost_of_living_index: 35.0, avg_monthly_utilities: 60, avg_monthly_groceries: 200, avg_monthly_transport: 25, description: "The Caribbean's oldest city — colonial charm meets tropical island life.", short_description: "The Caribbean's oldest city — colonial charm meets island life.", languages: ["Spanish"], currency: "DOP", timezone: "America/Santo_Domingo", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "32", country: "Puerto Rico", city: "San Juan", region: "San Juan", continent: "North America", flag_emoji: "🇵🇷", image_url: "", job_score: 68, education_score: 70, business_score: 72, tourism_score: 90, quality_of_life_score: 72, safety_score: 65, avg_rent_1br: 700, avg_rent_3br: 1500, cost_of_living_index: 55.0, avg_monthly_utilities: 120, avg_monthly_groceries: 350, avg_monthly_transport: 35, description: "A vibrant US territory — Caribbean beaches with American infrastructure and Latin soul.", short_description: "Caribbean beaches with American infrastructure and Latin soul.", languages: ["Spanish", "English"], currency: "USD", timezone: "America/Puerto_Rico", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "33", country: "Jamaica", city: "Kingston", region: "Kingston", continent: "North America", flag_emoji: "🇯🇲", image_url: "", job_score: 58, education_score: 60, business_score: 65, tourism_score: 82, quality_of_life_score: 62, safety_score: 45, avg_rent_1br: 350, avg_rent_3br: 750, cost_of_living_index: 30.0, avg_monthly_utilities: 55, avg_monthly_groceries: 200, avg_monthly_transport: 25, description: "Jamaica's capital — reggae, warm hospitality, and the pulse of Caribbean culture.", short_description: "Reggae, warmth, and the heart of Caribbean culture.", languages: ["English", "Jamaican Creole"], currency: "JMD", timezone: "America/Jamaica", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "34", country: "Trinidad and Tobago", city: "Port of Spain", region: "Port of Spain", continent: "North America", flag_emoji: "🇹🇹", image_url: "", job_score: 68, education_score: 65, business_score: 72, tourism_score: 70, quality_of_life_score: 70, safety_score: 55, avg_rent_1br: 500, avg_rent_3br: 1100, cost_of_living_index: 40.0, avg_monthly_utilities: 70, avg_monthly_groceries: 250, avg_monthly_transport: 30, description: "The Caribbean's energy capital — Carnival, diverse cultures, and a strong economy.", short_description: "Caribbean energy capital — Carnival, diversity, and economic strength.", languages: ["English"], currency: "TTD", timezone: "America/Port_of_Spain", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "35", country: "Cuba", city: "Havana", region: "Havana", continent: "North America", flag_emoji: "🇨🇺", image_url: "", job_score: 55, education_score: 65, business_score: 50, tourism_score: 90, quality_of_life_score: 60, safety_score: 70, avg_rent_1br: 200, avg_rent_3br: 500, cost_of_living_index: 25.0, avg_monthly_utilities: 40, avg_monthly_groceries: 150, avg_monthly_transport: 15, description: "A timeless Caribbean capital — classic cars, colonial architecture, and vibrant culture.", short_description: "Timeless Caribbean capital — classic cars, colonial architecture, and soul.", languages: ["Spanish"], currency: "CUP", timezone: "America/Havana", visa_info_url: "", is_featured: false, created_at: "2024-01-01", updated_at: "2024-01-01" },
    { id: "36", country: "Bahamas", city: "Nassau", region: "New Providence", continent: "North America", flag_emoji: "🇧🇸", image_url: "", job_score: 65, education_score: 60, business_score: 72, tourism_score: 95, quality_of_life_score: 75, safety_score: 70, avg_rent_1br: 1200, avg_rent_3br: 2500, cost_of_living_index: 75.0, avg_monthly_utilities: 150, avg_monthly_groceries: 450, avg_monthly_transport: 40, description: "Tropical paradise — turquoise waters, tax-free living, and world-class resorts.", short_description: "Tropical paradise — turquoise waters and tax-free island living.", languages: ["English"], currency: "BSD", timezone: "America/Nassau", visa_info_url: "", is_featured: true, created_at: "2024-01-01", updated_at: "2024-01-01" },
  ];

// =============================================================================
// Server Functions
// =============================================================================

/** Get all destinations, optionally filtered by continent */
export const getDestinations = createServerFn({ method: "GET" }).handler(
  async (data: unknown) => {
    const { continent } = (data || {}) as { continent?: string };

    let results = [...SEED_DESTINATIONS];
    if (continent) {
      results = results.filter((d) => d.continent === continent);
    }
    return results.sort((a, b) => (a.is_featured === b.is_featured ? 0 : a.is_featured ? -1 : 1));
  },
);

/** Get featured destinations */
export const getFeaturedDestinations = createServerFn({ method: "GET" }).handler(
  async () => {
    return SEED_DESTINATIONS.filter((d) => d.is_featured).slice(0, 6);
  },
);

/** Get a single destination by ID */
export const getDestinationById = createServerFn({ method: "GET" }).handler(
  async (data: unknown) => {
    const { id } = (data || {}) as { id: string };
    return SEED_DESTINATIONS.find((d) => d.id === id) || null;
  },
);

/** Search destinations by city or country name */
export const searchDestinations = createServerFn({ method: "GET" }).handler(
  async (data: unknown) => {
    const { query } = (data || {}) as { query: string };
    if (!query || query.trim().length < 2) return SEED_DESTINATIONS;
    const q = query.toLowerCase();
    return SEED_DESTINATIONS.filter(
      (d) =>
        d.city.toLowerCase().includes(q) ||
        d.country.toLowerCase().includes(q) ||
        d.continent.toLowerCase().includes(q),
    );
  },
);

/** Get all continents */
export const getContinents = createServerFn({ method: "GET" }).handler(
  async () => {
    const continents = [...new Set(SEED_DESTINATIONS.map((d) => d.continent))];
    return continents.sort();
  },
);

/** Compare two destinations side by side */
export const compareDestinations = createServerFn({ method: "GET" }).handler(
  async (data: unknown) => {
    const { ids } = (data || {}) as { ids: string[] };
    if (!ids || ids.length < 2) return [];
    return SEED_DESTINATIONS.filter((d) => ids.includes(d.id));
  },
);