-- =============================================================================
-- Global Mobilis — Africa, Caribbean & South America Destinations
-- =============================================================================

-- Africa
INSERT INTO destinations (country, city, region, continent, flag_emoji, job_score, education_score, business_score, tourism_score, quality_of_life_score, safety_score, avg_rent_1br, avg_rent_3br, cost_of_living_index, avg_monthly_utilities, avg_monthly_groceries, avg_monthly_transport, description, short_description, languages, currency, timezone, is_featured) VALUES
('South Africa', 'Cape Town', 'Western Cape', 'Africa', '🇿🇦', 72, 75, 78, 95, 82, 60, 550, 1200, 42.0, 80, 280, 60, 'A breathtaking coastal city where Table Mountain meets vibrant culture and a growing tech scene.', 'Stunning coastal city with mountains, beaches, and a thriving startup ecosystem.', ARRAY['English', 'Afrikaans', 'Xhosa'], 'ZAR', 'Africa/Johannesburg', true),
('Kenya', 'Nairobi', 'Nairobi', 'Africa', '🇰🇪', 78, 72, 85, 70, 65, 55, 500, 1100, 38.0, 70, 250, 50, 'East Africa''s economic powerhouse — a hub for innovation, tech startups, and safari adventures.', 'East Africa''s tech hub — innovation, safaris, and a booming economy.', ARRAY['Swahili', 'English'], 'KES', 'Africa/Nairobi', true),
('Nigeria', 'Lagos', 'Lagos', 'Africa', '🇳🇬', 80, 65, 88, 60, 55, 40, 600, 1500, 35.0, 100, 300, 40, 'Africa''s largest city — a dynamic megacity of entrepreneurs, creatives, and nonstop energy.', 'Africa''s largest city — entrepreneurial energy meets vibrant culture.', ARRAY['English', 'Yoruba', 'Hausa', 'Igbo'], 'NGN', 'Africa/Lagos', false),
('Ghana', 'Accra', 'Greater Accra', 'Africa', '🇬🇭', 68, 70, 72, 75, 70, 65, 400, 900, 32.0, 60, 200, 35, 'West Africa''s gem — friendly, stable, and growing fast with a rich cultural heritage.', 'West Africa''s friendliest city — stable, welcoming, and on the rise.', ARRAY['English', 'Twi', 'Ga'], 'GHS', 'Africa/Accra', true),
('Morocco', 'Casablanca', 'Casablanca-Settat', 'Africa', '🇲🇦', 70, 68, 75, 80, 72, 70, 450, 1000, 38.0, 55, 220, 40, 'Morocco''s economic capital — where modern business meets historic charm and Atlantic breezes.', 'Morocco''s economic hub — business meets history by the Atlantic.', ARRAY['Arabic', 'Berber', 'French'], 'MAD', 'Africa/Casablanca', false),
('Rwanda', 'Kigali', 'Kigali', 'Africa', '🇷🇼', 72, 78, 70, 75, 78, 85, 400, 850, 30.0, 50, 180, 30, 'Africa''s cleanest city — a model of modern urban development and tech innovation.', 'Africa''s cleanest city — modern, safe, and innovation-driven.', ARRAY['Kinyarwanda', 'English', 'French', 'Swahili'], 'RWF', 'Africa/Kigali', false);

-- South America
INSERT INTO destinations (country, city, region, continent, flag_emoji, job_score, education_score, business_score, tourism_score, quality_of_life_score, safety_score, avg_rent_1br, avg_rent_3br, cost_of_living_index, avg_monthly_utilities, avg_monthly_groceries, avg_monthly_transport, description, short_description, languages, currency, timezone, is_featured) VALUES
('Argentina', 'Buenos Aires', 'Buenos Aires', 'South America', '🇦🇷', 72, 75, 78, 90, 75, 55, 500, 1000, 40.0, 80, 250, 30, 'The Paris of South America — tango, steak, and a passionate European-infused culture.', 'The Paris of South America — tango, steak, and European charm.', ARRAY['Spanish'], 'ARS', 'America/Argentina/Buenos_Aires', true),
('Brazil', 'São Paulo', 'São Paulo', 'South America', '🇧🇷', 85, 80, 88, 72, 68, 40, 600, 1300, 45.0, 100, 280, 60, 'The economic engine of Latin America — a sprawling metropolis of business, culture, and diversity.', 'Latin America''s economic powerhouse — business, culture, and endless energy.', ARRAY['Portuguese'], 'BRL', 'America/Sao_Paulo', true),
('Brazil', 'Rio de Janeiro', 'Rio de Janeiro', 'South America', '🇧🇷', 65, 70, 72, 95, 68, 35, 550, 1200, 42.0, 90, 260, 55, 'The Marvelous City — iconic beaches, samba, and breathtaking natural beauty.', 'The Marvelous City — beaches, samba, and breathtaking landscapes.', ARRAY['Portuguese'], 'BRL', 'America/Sao_Paulo', true),
('Chile', 'Santiago', 'Santiago Metropolitan', 'South America', '🇨🇱', 78, 80, 82, 78, 82, 70, 600, 1300, 48.0, 90, 280, 55, 'Chile''s modern capital — surrounded by the Andes, with a stable economy and excellent quality of life.', 'Modern Andean capital — stability, quality of life, and mountain views.', ARRAY['Spanish'], 'CLP', 'America/Santiago', true),
('Colombia', 'Bogotá', 'Bogotá', 'South America', '🇨🇴', 72, 72, 78, 70, 68, 50, 400, 900, 32.0, 70, 200, 35, 'Colombia''s high-altitude capital — a renaissance city of art, gastronomy, and entrepreneurship.', 'Colombia''s renaissance city — art, gastronomy, and entrepreneurship at altitude.', ARRAY['Spanish'], 'COP', 'America/Bogota', false),
('Peru', 'Lima', 'Lima', 'South America', '🇵🇪', 70, 68, 72, 85, 68, 45, 450, 950, 35.0, 65, 220, 35, 'Peru''s coastal capital — world-class cuisine, colonial history, and a gateway to Machu Picchu.', 'World-class cuisine, colonial history, gateway to Machu Picchu.', ARRAY['Spanish', 'Quechua'], 'PEN', 'America/Lima', false);

-- Caribbean
INSERT INTO destinations (country, city, region, continent, flag_emoji, job_score, education_score, business_score, tourism_score, quality_of_life_score, safety_score, avg_rent_1br, avg_rent_3br, cost_of_living_index, avg_monthly_utilities, avg_monthly_groceries, avg_monthly_transport, description, short_description, languages, currency, timezone, is_featured) VALUES
('Dominican Republic', 'Santo Domingo', 'National District', 'North America', '🇩🇴', 62, 65, 70, 88, 68, 50, 400, 850, 35.0, 60, 200, 25, 'The Caribbean''s oldest city — colonial charm meets tropical island life.', 'The Caribbean''s oldest city — colonial charm meets island life.', ARRAY['Spanish'], 'DOP', 'America/Santo_Domingo', true),
('Puerto Rico', 'San Juan', 'San Juan', 'North America', '🇵🇷', 68, 70, 72, 90, 72, 65, 700, 1500, 55.0, 120, 350, 35, 'A vibrant US territory — Caribbean beaches with American infrastructure and Latin soul.', 'Caribbean beaches with American infrastructure and Latin soul.', ARRAY['Spanish', 'English'], 'USD', 'America/Puerto_Rico', true),
('Jamaica', 'Kingston', 'Kingston', 'North America', '🇯🇲', 58, 60, 65, 82, 62, 45, 350, 750, 30.0, 55, 200, 25, 'Jamaica''s capital — reggae, warm hospitality, and the pulse of Caribbean culture.', 'Reggae, warmth, and the heart of Caribbean culture.', ARRAY['English', 'Jamaican Creole'], 'JMD', 'America/Jamaica', false),
('Trinidad and Tobago', 'Port of Spain', 'Port of Spain', 'North America', '🇹🇹', 68, 65, 72, 70, 70, 55, 500, 1100, 40.0, 70, 250, 30, 'The Caribbean''s energy capital — Carnival, diverse cultures, and a strong economy.', 'Caribbean energy capital — Carnival, diversity, and economic strength.', ARRAY['English'], 'TTD', 'America/Port_of_Spain', false),
('Cuba', 'Havana', 'Havana', 'North America', '🇨🇺', 55, 65, 50, 90, 60, 70, 200, 500, 25.0, 40, 150, 15, 'A timeless Caribbean capital — classic cars, colonial architecture, and vibrant culture.', 'Timeless Caribbean capital — classic cars, colonial architecture, and soul.', ARRAY['Spanish'], 'CUP', 'America/Havana', false),
('Bahamas', 'Nassau', 'New Providence', 'North America', '🇧🇸', 65, 60, 72, 95, 75, 70, 1200, 2500, 75.0, 150, 450, 40, 'Tropical paradise — turquoise waters, tax-free living, and world-class resorts.', 'Tropical paradise — turquoise waters and tax-free island living.', ARRAY['English'], 'BSD', 'America/Nassau', true);